### ISSUE TITLE
camelCase events

### ISSUE THREAD

**Issue by nattyluke** [promosis/vue-cookie-accept-decline#10]
I have a problem with camelCase events.
When I use:
`			<vue-cookie-accept-decline  v-on:clickedAccept="cookieClickedAccept"
										:element-id="'filemanager-app'">
			</vue-cookie-accept-decline>
`
I get the following Console Message: You cant use camelcase in dom, use _clicked-accept_ instead.
But when i use clicked-accept, the function cookieClickedAccept is not entered.
So i compiled vue-cookie-accept-decline on my own changing the name clickedAccept to clicked-accept. 
Now everything is working fine.
I'm a vue starter so maybe you can help me. I guess the Problem is i dont use a Component, i write my code directly in the dom.
Is it better to wrap `<vue-cookie-accept-decline>` in an own component so i dont get the camel-case problem or is the mistake on your side (better not use any camelcase)

Thanks for helping and clearing things up and for the nice code

**Comment by johndatserakis** [comment]
Hey bud - yea this is happening because you are writing your code directly in the dom. That is an alternative way to use Vue -  that I honestly have never done - so that's why this issue doesn't bite most users. (I'm always either using Vue-CLI or WebPack with Vue-Loader).

Regardless - I do agree it should be fixed to allow proper support to those writing their components directly in the dom.

So I just pushed [v5.0.0](https://github.com/promosis/vue-cookie-accept-decline/pull/12) - it includes the fix for this - and now you should be able to listen to the events without issue. Sorry about that! Thank you.

**Comment by nattyluke** [comment]
good work thank you too
